### ISSUE TITLE
Shipping broken in flathub

### ISSUE THREAD

**Issue by s1nistr4** [flathub/rest.insomnia.Insomnia#58] opened 2023-09-05 20:26 UTC
`
Error: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /run/user/1000/app/rest.insomnia.Insomnia/.org.chromium.Chromium.7zCTvn)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/main/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)

`

**Comment by tgm-git** [comment] 2023-09-06 11:21
This seems to be a duplicate of issue  #57

**Comment by hfiguiere** [comment] 2023-09-07 01:57
dupe of #57 

next build should fix this.

**Closed by hfiguiere** 2023-09-07 01:57 UTC

**Comment by tgm-git** [comment] 2023-09-08 14:00
I can confirm that v2023.5.7 resolved this issue
